name: Auto Merge Pull Request

on:
  pull_request_review:
    types:
      - submitted

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Merge PR
        run: |
          # main 브렌치 가리키는지 확인하기
          if [[ ${{ github.event.pull_request.base.ref }} == "main" ]]; then
            # Check if the PR is approved
            APPROVALS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -X GET https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
              | grep '"state": "APPROVED"' | wc -l)
            if [[ "$APPROVALS" -gt "0" ]]; then
              # Merge the PR
              git config user.name "GitHub Actions"
              git config user.email "actions@github.com"
              git fetch origin "+refs/pull/${{ github.event.pull_request.number }}/merge:"
              git merge FETCH_HEAD --no-edit
              git push origin main
            else
              echo "Skipping merge because the PR is not approved."
            fi
          else
            echo "Skipping merge because the PR is not targeting 'main' branch."
          fi
