name: Django Tests

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # - name: Lint with flake8
      #   run: |
      #     pip install flake8
      #     flake8
      - name: Coverage report
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report
      - name: Django Tests
        run: |
          python manage.py test



# jobs:
#   test-lint:
#     name: Test
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_PASSWORD }}
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Test
#         run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
