name: Docker Compose CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Pull xhub-django image
      run: docker pull starmireu/xhub-django:latest

    - name: Start containers using Docker Compose
      run: |
        DB_NAME=${{ secrets.DB_NAME }} DB_USER=${{ secrets.DB_USER }} DB_PASSWORD=${{ secrets.DB_PASSWORD }} DB_HOST=${{ secrets.DB_HOST }} DB_PORT=${{ secrets.DB_PORT }} SECRET_KEY=${{ secrets.SECRET_KEY }} DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }} docker-compose up -d

    - name: Print PostgreSQL logs
      run: docker logs xhub_db_1

    - name: List all running containers
      run: docker ps -a    

    - name: Run tests
      run: |
        docker exec xhub_django_1 python manage.py test

    - name: Stop and remove containers
      run: docker-compose down

    - name: Print container logs (on failure)
      if: failure()
      run: docker-compose logs
    