name: Update Lightsail
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }} # 환경 변수를 설정합니다. GitHub Secrets에서 SECRET_KEY를 가져옵니다.
      DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python manage.py test player
  
    
  update-lighthouse:
    needs: test  # Ensuring deployment only happens after tests succeed
    runs-on: ubuntu-latest
    steps:
    - name: Add user to docker group
      run: sudo usermod -aG docker $USER && sudo service docker restart
        
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: SSH and Update
      run: |
        ssh-keyscan 54.248.217.183 >> ~/.ssh/known_hosts
        ssh -v ubuntu@54.248.217.183 <<EOF
          cd /home/ubuntu/XHub
          git checkout main
          git pull origin main
          ./docker-initial.sh
        EOF
