name: Update Lighthouse
on:
  push:
    branches:
      - develop

jobs:
  update-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Add user to docker group
        run: sudo usermod -aG docker $USER && sudo service docker restart
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH and Update
        run: |
          echo "54.248.217.183 $(ssh-keyscan -H 54.248.217.183)" >> ~/.ssh/known_hosts
          
          # SSH into the server
          ssh Ubuntu@54.248.217.183 <<EOF
            # Navigate to the Lighthouse directory
            cd /home/ubuntu/XHub
            # Pull the latest version of the repository
            git pull origin develop
            # Rebuild and restart the Docker services
            docker-compose --env-file /home/ubuntu/XHub/.env down
            docker-compose --env-file /home/ubuntu/XHub/.env build
            docker-compose --env-file /home/ubuntu/XHub/.env up -d
          EOF
